// angular-app/src/app/components/waitlist-form/waitlist-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-waitlist-form',
  templateUrl: './waitlist-form.component.html',
  styleUrls: ['./waitlist-form.component.scss']
})
export class WaitlistFormComponent {
  waitlistForm: FormGroup;
  submitted = false;
  success = false;
  errorMessage = '';
  isSubmitting = false;

  constructor(private fb: FormBuilder, private http: HttpClient) {
    this.waitlistForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.pattern(/^[0-9+ -]{10,15}$/)]],
      message: ['']
    });
  }

  get form() { 
    return this.waitlistForm.controls; 
  }

  onSubmit() {
    this.submitted = true;
    this.success = false;
    this.errorMessage = '';
    
    if (this.waitlistForm.invalid) {
      return;
    }
    
    this.isSubmitting = true;
    
    this.http.post('/api/waitlist', this.waitlistForm.value)
      .subscribe({
        next: (response) => {
          this.success = true;
          this.isSubmitting = false;
          this.waitlistForm.reset();
          this.submitted = false;
        },
        error: (error) => {
          console.error('Error submitting waitlist form:', error);
          this.errorMessage = error.error?.message || 'Failed to submit form. Please try again later.';
          this.isSubmitting = false;
        }
      });
  }
}
<section id="contact" class="waitlist-section section">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 waitlist-content">
        <h2 class="section-title">Join Our Waitlist</h2>
        <p class="waitlist-intro">
          Be the first to experience our premium Ayurvedic products. Sign up for early access, exclusive offers, and updates on our launch.
        </p>
        <div class="waitlist-features">
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Early access to our product lineup</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Special discounts for waitlist members</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Personalized dosha consultation</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Exclusive wellness content</span>
          </div>
        </div>
      </div>
      
      <div class="col-lg-6 waitlist-form-container">
        <div class="form-wrapper">
          <!-- Success message -->
          <div class="form-success" *ngIf="success">
            <div class="success-icon">
              <i class="fas fa-check-circle"></i>
            </div>
            <h3>Thank You!</h3>
            <p>Your submission has been received. We'll contact you soon with exclusive updates.</p>
          </div>
          
          <!-- Form -->
          <form [formGroup]="waitlistForm" (ngSubmit)="onSubmit()" *ngIf="!success">
            <div class="form-group">
              <label for="name">Full Name</label>
              <input 
                type="text" 
                id="name" 
                formControlName="name" 
                class="form-control"
                [ngClass]="{ 'is-invalid': submitted && form['name'].errors }"
                placeholder="Your name">
              <div *ngIf="submitted && form['name'].errors" class="invalid-feedback">
                <div *ngIf="form['name'].errors['required']">Name is required</div>
                <div *ngIf="form['name'].errors['minlength']">Name must be at least 2 characters</div>
              </div>
            </div>
            
            <div class="form-group">
              <label for="email">Email Address</label>
              <input 
                type="email" 
                id="email" 
                formControlName="email" 
                class="form-control"
                [ngClass]="{ 'is-invalid': submitted && form['email'].errors }"
                placeholder="Your email">
              <div *ngIf="submitted && form['email'].errors" class="invalid-feedback">
                <div *ngIf="form['email'].errors['required']">Email is required</div>
                <div *ngIf="form['email'].errors['email']">Please enter a valid email address</div>
              </div>
            </div>
            
            <div class="form-group">
              <label for="phone">Phone Number (Optional)</label>
              <input 
                type="tel" 
                id="phone" 
                formControlName="phone" 
                class="form-control"
                [ngClass]="{ 'is-invalid': submitted && form['phone'].errors }"
                placeholder="Your phone number">
              <div *ngIf="submitted && form['phone'].errors" class="invalid-feedback">
                <div *ngIf="form['phone'].errors['pattern']">Please enter a valid phone number</div>
              </div>
            </div>
            
            <div class="form-group">
              <label for="message">Message (Optional)</label>
              <textarea 
                id="message" 
                formControlName="message" 
                class="form-control" 
                rows="4"
                placeholder="What are you most excited about?"></textarea>
            </div>
            
            <!-- Error message -->
            <div class="alert alert-danger" *ngIf="errorMessage">
              {{ errorMessage }}
            </div>
            
            <button 
              type="submit" 
              class="btn-primary btn-block"
              [disabled]="isSubmitting">
              <span *ngIf="isSubmitting">
                <i class="fas fa-spinner fa-spin"></i> Submitting...
              </span>
              <span *ngIf="!isSubmitting">Join the Waitlist</span>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

// client/src/components/WaitlistForm.tsx
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { z } from "zod";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";

// Waitlist form schema
const waitlistSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters" }),
  email: z.string().email({ message: "Please enter a valid email address" }),
  phone: z.string().optional(),
  message: z.string().optional(),
});

type WaitlistFormValues = z.infer<typeof waitlistSchema>;

export default function WaitlistForm() {
  const { toast } = useToast();
  const [submitted, setSubmitted] = useState(false);

  // Initialize form
  const form = useForm<WaitlistFormValues>({
    resolver: zodResolver(waitlistSchema),
    defaultValues: {
      name: "",
      email: "",
      phone: "",
      message: "",
    },
  });

  // Handle form submission using mutation
  const { mutate, isPending } = useMutation({
    mutationFn: async (values: WaitlistFormValues) => {
      const res = await apiRequest("POST", "/api/waitlist", values);
      return res.json();
    },
    onSuccess: () => {
      toast({
        title: "Success!",
        description: "You've been added to our waitlist. We'll be in touch soon!",
      });
      setSubmitted(true);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to join waitlist. Please try again.",
        variant: "destructive",
      });
    },
  });

  // Form submission handler
  const onSubmit = (values: WaitlistFormValues) => {
    mutate(values);
  };

  // If form is successfully submitted, show the success message
  if (submitted) {
    return (
      <div className="text-center py-8">
        <h3 className="text-2xl font-semibold text-primary mb-4">Thank You for Joining Our Waitlist!</h3>
        <p className="text-lg mb-4">
          We're thrilled to have you join us on this journey to wellness. You'll be among the first to know when our new products launch.
        </p>
        <p>We'll be in touch soon with exclusive updates and offers.</p>
      </div>
    );
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Full Name</FormLabel>
                <FormControl>
                  <Input placeholder="Your name" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Email</FormLabel>
                <FormControl>
                  <Input placeholder="your.email@example.com" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <FormField
          control={form.control}
          name="phone"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Phone (Optional)</FormLabel>
              <FormControl>
                <Input placeholder="Your phone number" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <FormField
          control={form.control}
          name="message"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Message (Optional)</FormLabel>
              <FormControl>
                <Textarea
                  placeholder="Tell us what products you're interested in or any specific wellness concerns..."
                  rows={4}
                  {...field}
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />

        <Button type="submit" className="w-full" size="lg" disabled={isPending}>
          {isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Processing...
            </>
          ) : (
            "Join the Waitlist"
          )}
        </Button>
      </form>
    </Form>
  );
}
